{
 "title": "raspberrypi test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "BME280", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "pressure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "humidity", "legendFormat": "__auto" }
   ]
  },
  { "title": "NOVA SDS011", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "pm2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "pmtwofive", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "pm10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "pmten", "legendFormat": "__auto" }
   ]
  }
 ]
}